version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.0.0
  aws-s3: circleci/aws-s3@3.0

jobs:
  build-front:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: npm run frontend:install
      - run:
          name: Front-End build
          command: npm run frontend:build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  test-front: 
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Front-End test
          command: npm run frontend:test

  deploy-front: 
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup 
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          arguments: |
            --delete
          from: frontend/build/
          to: $FRONT_BUCKET

  build-back:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - run: mkdir backend/cert
      - aws-s3/copy:
          from: $EB_ENV_CERT
          to: backend/cert/server.cert
      - aws-s3/copy:
          from: $EB_ENV_KEY
          to: backend/cert/server.key
      - run:
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Back-End build
          command: npm run backend:build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  test-back: 
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: ~/project
      - run:
          name: Back-End test
          command: npm run backend:test

  deploy-back: 
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          command: |
            cd backend
            eb deploy
            eb status

  
workflows:
  build-deploy:
    jobs:
      - build-front
      - test-front:
          requires:
            - build-front
      - deploy-front:
          requires:
            - test-front
          filters:
            branches:
              only: main
      - build-back
      - test-back:
          requires:
            - build-back
      - deploy-back:
          requires:
            - test-back
          filters:
            branches:
              only: main
      
