version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .

  build-front:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: npm run frontend:install
      - run:
          name: Front-End build
          command: npm run frontend:build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  test-front: 
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Front-End test
          command: npm run frontend:test

  deploy-front: 
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup:
          configure-default-region: true 
          configure-profile-region: true 
          disable-aws-pager: true 
          override-installed: false 
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          profile-name: AWS_PROFILE_NAME        
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - checkout
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Front-End deploy
          command: npm run frontend:deploy

workflows:
  docker-build:
    jobs:
      - build-docker
      
  front-build-deploy:
    jobs:
      - build-docker
      - build-front
          requires:
            - docker-build
      - test-front:
          requires:
            - build-front
      - deploy-front:
          requires:
            - test-front
          filters:
            branches:
              only: main
