branch-defaults:
  default:
    environment: Imageprocessingbackend-env
environment-defaults:
  Imageprocessingbackend-env:
    branch: main
    repository: null
global:
  application_name: image-processing-backend
  branch: main
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: image-processing-backend
  sc: git
  workspace_type: Application
